name: v2-to-v3 test

on:
  push:
  pull_request:

env:
  PACT_BROKER_BASE_URL: https://saf.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        folder: [v2, v3]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x for ${{ matrix.folder }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: ${{ matrix.folder }}/package-lock.json
      - run: npm ci
        working-directory: ${{ matrix.folder }}
      - run: npm run test:consumer
        name: test ${{ matrix.folder }}
        working-directory: ${{ matrix.folder }}
      - run: npm run publish
        name: test ${{ matrix.folder }}
        working-directory: ${{ matrix.folder }}
      - run: npm run test:provider
        name: test ${{ matrix.folder }}
        working-directory: ${{ matrix.folder }}
